### ISSUE TITLE
Attempting to use alloc feature while no_std doesn't compile

### ISSUE THREAD

**Issue by ghost** [jhg/opaque-pointer-rs#4]
rustc 1.68.2 (9eb3afe9e 2023-03-27)
cargo 1.68.2 (6feb7c9cf 2023-03-26)

In my no_std library project, adding this dependency:
`
opaque-pointer = { version = "0.8.6", default-features = false, features = ["alloc"] }
`

Causes compiler errors complaining about "can't find crate for `std`":
`error[E0433]: failed to resolve: use of undeclared crate or module `std`                                                                     
 --> C:\Users\xxx\.cargo\registry\src\github.com-1ecc6299db9ec823\opaque-pointer-0.8.6\src\error.rs:3:5
  |
3 | use std::str::Utf8Error;
  |     ^^^ use of undeclared crate or module `std`

error[E0433]: failed to resolve: use of undeclared crate or module `std`
  --> C:\Users\xxx\\.cargo\registry\src\github.com-1ecc6299db9ec823\opaque-pointer-0.8.6\src\error.rs:19:6
   |
19 | impl std::fmt::Display for PointerError {
   |      ^^^ use of undeclared crate or module `std`

error[E0433]: failed to resolve: use of undeclared crate or module `std`
  --> C:\Users\xxx\\.cargo\registry\src\github.com-1ecc6299db9ec823\opaque-pointer-0.8.6\src\error.rs:20:27
   |
20 |     fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
   |                           ^^^ use of undeclared crate or module `std`

error[E0433]: failed to resolve: use of undeclared crate or module `std`
  --> C:\Users\xxx\\.cargo\registry\src\github.com-1ecc6299db9ec823\opaque-pointer-0.8.6\src\error.rs:20:51
   |
20 |     fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
   |                                                   ^^^ use of undeclared crate or module `std`

error[E0433]: failed to resolve: use of undeclared crate or module `std`
  --> C:\Users\xxx\\.cargo\registry\src\github.com-1ecc6299db9ec823\opaque-pointer-0.8.6\src\error.rs:35:6
   |
35 | impl std::error::Error for PointerError {
   |      ^^^ use of undeclared crate or module `std`

error[E0433]: failed to resolve: use of undeclared crate or module `std`
  --> C:\Users\xxx\\.cargo\registry\src\github.com-1ecc6299db9ec823\opaque-pointer-0.8.6\src\error.rs:36:38
   |
36 |     fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
   |                                      ^^^ use of undeclared crate or module `std`

error[E0433]: failed to resolve: use of undeclared crate or module `std`
  --> C:\Users\xxx\\.cargo\registry\src\github.com-1ecc6299db9ec823\opaque-pointer-0.8.6\src\lib.rs:98:5
   |
98 |     std::mem::drop(own_back(pointer));
   |     ^^^ use of undeclared crate or module `std``

**Comment by jhg** [comment]
Sorry for the delay reply. I will check settings about notifications to see issues faster, sorry.

A new [version (0.8.7) is published](https://crates.io/crates/opaque-pointer/0.8.7), that must works. Also the tests now run with alloc feature to find errors like this one.

Thanks.
